name: Update QuantumultX Configuration

on:
  schedule:
    - cron: '0 23 * * *'  # 每天23:00运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-configuration:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用内置的 GitHub Token

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch the latest configuration file
      run: |
        curl -o QuantumultX.conf https://raw.githubusercontent.com/ddgksf2013/Profile/master/QuantumultX.conf
        cat QuantumultX.conf  # 调试输出

    - name: Modify the configuration
      run: |
        # 将 "Color" 替换为 "mini"
        sed -i 's/Color/mini/g' QuantumultX.conf

        # 在 "wifi2: all_direct" 下一行添加 "ssid_suspended_list=Live_5G"
        sed -i '/^wifi2: all_direct$/a ssid_suspended_list=Live_5G' QuantumultX.conf

        cat QuantumultX.conf  # 调试输出

    - name: Check for changes and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # 检查是否有更改
        if [ -n "$(git status --porcelain)" ]; then
          git add QuantumultX.conf
          git commit -m "Updated QuantumultX.conf"
          git push --quiet "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        fi

    - name: Compare with remote file
      run: |
        # 获取远程文件内容
        curl -o remote.conf https://raw.githubusercontent.com/ddgksf2013/Profile/master/QuantumultX.conf

        # 比较本地和远程文件内容是否一致
        if ! cmp -s QuantumultX.conf remote.conf; then
          echo "Remote file has changed. Updating local file..."
          mv remote.conf QuantumultX.conf

          # 再次执行修改步骤
          sed -i 's/Color/mini/g' QuantumultX.conf
          sed -i '/^wifi2: all_direct$/a ssid_suspended_list=Live_5G' QuantumultX.conf

          # 提交更改
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add QuantumultX.conf
          git commit -m "Synced and updated QuantumultX.conf from remote"
          git push --quiet "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        else
          echo "No changes detected in remote file."
        fi
