name: Update QuantumultX.conf

on:
  schedule:
    - cron: "0 23 * * *"  # 每天 23 点运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update-conf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      # Step 4: 运行脚本
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_quantumultx.py
